const mongoose = require('mongoose');

const Payroll = require('./models/payroll_model.js');
const DB = require('./models/database.js')
const add_data_payroll = {
    populate_payroll: function(){
        var payrolls = [
            {
                Email: 'john.doe@example.com',
                Week: 0,
                Time_In_Weekday_Index: 4,
                
                Mon_Time_In: '08:00',
                Mon_Time_Out: '16:00',
                Mon_Hours: 8,
                Mon_Minutes: 0,
                Mon_OT_Hours: 0,
                Mon_OT_Compensation: 0,
                Mon_Late_Hours: 0,
                Mon_Late_Deduction: 0,
                Mon_Total_Pay: 80,
                Mon_Date: '2024-06-24',
                
                Tue_Time_In: '08:15',
                Tue_Time_Out: '16:45',
                Tue_Hours: 8,
                Tue_Minutes: 30,
                Tue_OT_Hours: 0,
                Tue_OT_Compensation: 0,
                Tue_Late_Hours: 1,
                Tue_Late_Deduction: 10,
                Tue_Total_Pay: 70,
                Tue_Date: '2024-06-25',
                
                Wed_Time_In: '08:30',
                Wed_Time_Out: '17:00',
                Wed_Hours: 8,
                Wed_Minutes: 30,
                Wed_OT_Hours: 0,
                Wed_OT_Compensation: 0,
                Wed_Late_Hours: 1,
                Wed_Late_Deduction: 10,
                Wed_Total_Pay: 70,
                Wed_Date: '2024-06-26',
                
                Thu_Time_In: '09:00',
                Thu_Time_Out: '17:30',
                Thu_Hours: 8,
                Thu_Minutes: 30,
                Thu_OT_Hours: 0,
                Thu_OT_Compensation: 0,
                Thu_Late_Hours: 2,
                Thu_Late_Deduction: 20,
                Thu_Total_Pay: 60,
                Thu_Date: '2024-06-27',
                
                Fri_Time_In: '09:15',
                Fri_Time_Out: '17:45',
                Fri_Hours: 8,
                Fri_Minutes: 30,
                Fri_OT_Hours: 0,
                Fri_OT_Compensation: 0,
                Fri_Late_Hours: 2,
                Fri_Late_Deduction: 20,
                Fri_Total_Pay: 60,
                Fri_Date: '2024-06-28',
        
                Sat_Time_In: '10:00',
                Sat_Time_Out: '14:00',
                Sat_Hours: 4,
                Sat_Minutes: 0,
                Sat_OT_Hours: 0,
                Sat_OT_Compensation: 0,
                Sat_Late_Hours: 2,
                Sat_Late_Deduction: 20,
                Sat_Total_Pay: 20,
                Sat_Date: '2024-06-29',
        
                Sun_Time_In: '10:30',
                Sun_Time_Out: '14:30',
                Sun_Hours: 4,
                Sun_Minutes: 0,
                Sun_OT_Hours: 0,
                Sun_OT_Compensation: 0,
                Sun_Late_Hours: 2,
                Sun_Late_Deduction: 20,
                Sun_Total_Pay: 20,
                Sun_Date: '2024-06-30',
        
                Weekly_Total_Advance: 50,
                Weekly_Total_Additional: 20,
                Weekly_Total_Deduction: 10,
                Weekly_Total_Pay: 500,
                Weekly_Hourly_Rate: 10
            },
            {
                Email: 'john.doe@example.com',
                Week: 1,
                Time_In_Weekday_Index: 0,
                
                Mon_Time_In: '08:00',
                Mon_Time_Out: '17:00',
                Mon_Hours: 9,
                Mon_Minutes: 0,
                Mon_OT_Hours: 1,
                Mon_OT_Compensation: 15,
                Mon_Late_Hours: 0,
                Mon_Late_Deduction: 0,
                Mon_Total_Pay: 105,
                Mon_Date: '2024-06-24',
                
                Tue_Time_In: '08:45',
                Tue_Time_Out: '16:45',
                Tue_Hours: 8,
                Tue_Minutes: 0,
                Tue_OT_Hours: 0,
                Tue_OT_Compensation: 0,
                Tue_Late_Hours: 1,
                Tue_Late_Deduction: 10,
                Tue_Total_Pay: 70,
                Tue_Date: '2024-06-25',
                
                Wed_Time_In: '09:15',
                Wed_Time_Out: '17:15',
                Wed_Hours: 8,
                Wed_Minutes: 0,
                Wed_OT_Hours: 0,
                Wed_OT_Compensation: 0,
                Wed_Late_Hours: 2,
                Wed_Late_Deduction: 20,
                Wed_Total_Pay: 60,
                Wed_Date: '2024-06-26',
                
                Thu_Time_In: '08:00',
                Thu_Time_Out: '18:00',
                Thu_Hours: 10,
                Thu_Minutes: 0,
                Thu_OT_Hours: 1,
                Thu_OT_Compensation: 15,
                Thu_Late_Hours: 0,
                Thu_Late_Deduction: 0,
                Thu_Total_Pay: 115,
                Thu_Date: '2024-06-27',
                
                Fri_Time_In: '08:30',
                Fri_Time_Out: '17:30',
                Fri_Hours: 9,
                Fri_Minutes: 0,
                Fri_OT_Hours: 1,
                Fri_OT_Compensation: 15,
                Fri_Late_Hours: 1,
                Fri_Late_Deduction: 10,
                Fri_Total_Pay: 95,
                Fri_Date: '2024-06-28',
        
                Sat_Time_In: '09:00',
                Sat_Time_Out: '13:00',
                Sat_Hours: 4,
                Sat_Minutes: 0,
                Sat_OT_Hours: 0,
                Sat_OT_Compensation: 0,
                Sat_Late_Hours: 1,
                Sat_Late_Deduction: 10,
                Sat_Total_Pay: 30,
                Sat_Date: '2024-06-29',
        
                Sun_Time_In: '10:00',
                Sun_Time_Out: '14:00',
                Sun_Hours: 4,
                Sun_Minutes: 0,
                Sun_OT_Hours: 0,
                Sun_OT_Compensation: 0,
                Sun_Late_Hours: 2,
                Sun_Late_Deduction: 20,
                Sun_Total_Pay: 20,
                Sun_Date: '2024-06-30',
        
                Weekly_Total_Advance: 30,
                Weekly_Total_Additional: 0,
                Weekly_Total_Deduction: 10,
                Weekly_Total_Pay: 495,
                Weekly_Hourly_Rate: 10
            },
            {
                Email: 'john.doe@example.com',
                Week: 2,
                Time_In_Weekday_Index: 0,
                
                Mon_Time_In: '08:00',
                Mon_Time_Out: '18:00',
                Mon_Hours: 10,
                Mon_Minutes: 0,
                Mon_OT_Hours: 1,
                Mon_OT_Compensation: 15,
                Mon_Late_Hours: 0,
                Mon_Late_Deduction: 0,
                Mon_Total_Pay: 115,
                Mon_Date: '2024-06-24',
                
                Tue_Time_In: '08:00',
                Tue_Time_Out: '17:00',
                Tue_Hours: 9,
                Tue_Minutes: 0,
                Tue_OT_Hours: 1,
                Tue_OT_Compensation: 15,
                Tue_Late_Hours: 0,
                Tue_Late_Deduction: 0,
                Tue_Total_Pay: 105,
                Tue_Date: '2024-06-25',
                
                Wed_Time_In: '08:30',
                Wed_Time_Out: '17:30',
                Wed_Hours: 9,
                Wed_Minutes: 0,
                Wed_OT_Hours: 1,
                Wed_OT_Compensation: 15,
                Wed_Late_Hours: 1,
                Wed_Late_Deduction: 10,
                Wed_Total_Pay: 95,
                Wed_Date: '2024-06-26',
                
                Thu_Time_In: '08:00',
                Thu_Time_Out: '17:00',
                Thu_Hours: 9,
                Thu_Minutes: 0,
                Thu_OT_Hours: 1,
                Thu_OT_Compensation: 15,
                Thu_Late_Hours: 0,
                Thu_Late_Deduction: 0,
                Thu_Total_Pay: 105,
                Thu_Date: '2024-06-27',
                
                Fri_Time_In: '09:00',
                Fri_Time_Out: '18:00',
                Fri_Hours: 9,
                Fri_Minutes: 0,
                Fri_OT_Hours: 1,
                Fri_OT_Compensation: 15,
                Fri_Late_Hours: 1,
                Fri_Late_Deduction: 10,
                Fri_Total_Pay: 95,
                Fri_Date: '2024-06-28',
            
                Sat_Time_In: '10:00',
                Sat_Time_Out: '14:00',
                Sat_Hours: 4,
                Sat_Minutes: 0,
                Sat_OT_Hours: 0,
                Sat_OT_Compensation: 0,
                Sat_Late_Hours: 2,
                Sat_Late_Deduction: 20,
                Sat_Total_Pay: 20,
                Sat_Date: '2024-06-29',
            
                Sun_Time_In: '10:30',
                Sun_Time_Out: '14:30',
                Sun_Hours: 4,
                Sun_Minutes: 0,
                Sun_OT_Hours: 0,
                Sun_OT_Compensation: 0,
                Sun_Late_Hours: 2,
                Sun_Late_Deduction: 20,
                Sun_Total_Pay: 20,
                Sun_Date: '2024-06-30',
            
                Weekly_Total_Advance: 30,
                Weekly_Total_Additional: 0,
                Weekly_Total_Deduction: 10,
                Weekly_Total_Pay: 565,
                Weekly_Hourly_Rate: 10
            }
        ]
        DB.insertMany(Payroll, payrolls)
    }
}

module.exports = add_data_payroll;